
#spring:
#  redis:
#    lettuce:
#      pool:
#        max-active: 500
#        max-idle: 500
#        max-wait: -1
#        min-idle: 10
#    port: 6379
#    host: 172.18.0.7
#server:
#  tomcat:
#    accept-count: 500
#    max-threads: 500
#    max-connections: 1000
#    min-spare-threads: 100


spring:
  redis:
    jedis:
      pool:
        max-active: 500
        max-idle: 500
        max-wait: -1
        min-idle: 10
    port: 6379
#这个配置会快一点
server:
  port: 8886
  tomcat:
    accept-count: 100
    max-threads: 60
    max-connections: 500
    min-spare-threads: 50