
server:
  tomcat:
    min-spare-threads: 50
    max-threads: 500
    max-connections: 500
  port: 8884

spring:
#  redis:
#    jedis:
#      pool:
#        max-active: 500 # 连接池最大连接数
#    #        max-idle: 8 #连接池中的最大空闲连接
#    #        max-wait: -1 #连接池最大阻塞等待时间，若使用负值表示没有限制
#    #        min-idle: 0  # 连接池中的最小空闲连接
#    database: 2
#    host: 172.18.0.7
#    port: 6379
  datasource:
    data-password: tdf
    data-username: TDF
    driver-class-name: com.kingbase8.Driver
    password: tdf
    url: jdbc:kingbase8://172.18.0.7:54321/TESTB
    username: TDF
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 20
  jpa:
    database-platform: org.hibernate.dialect.Kingbase8Dialect
    hibernate:
      ddl-auto: create

#spring:
#  redis:
#    jedis:
#      pool:
#        max-active: 500 # 连接池最大连接数
#    #        max-idle: 8 #连接池中的最大空闲连接
#    #        max-wait: -1 #连接池最大阻塞等待时间，若使用负值表示没有限制
#    #        min-idle: 0  # 连接池中的最小空闲连接
#    database: 2
#    host: 192.168.70.44
#    password: 123456
#    port: 6390
#  datasource:
#    driver-class-name: "com.mysql.cj.jdbc.Driver"     # mysql 8时候配置
#    url: "jdbc:mysql://192.168.70.44:3306/TDFTEST?serverTimezone=GMT%2B8&amp&characterEncoding=utf-8&useSSL=false"  #  mysql 8时候配置
#    # url=jdbc:mysql://127.0.0.1:3306/tdf?useUnicode=true&characterEncoding=utf-8     # mysql 8以下配置
#    # type=com.zaxxer.hikari.HikariDataSource    # mysql 8以下配置
#    username: root
#    password: admin
#    data-username: root
#    data-password: admin
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#       ddl-auto: create-drop
